language: node_js

node_js:
  - "4.0.0"

# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master

before_script:
  - npm install -g mocha
  - npm install -g istanbul